### ISSUE TITLE
Live tests Zodiac roles

### ISSUE THREAD

**Issue by MathisGD** [morpho-org/morpho-optimizers#1387]
I would be great to test that the Zodiac roles module is up to date (for when we add or rename governance functions).

I don't really know yet what form it should have though.

**Comment by MathisGD** [comment]
I see two paths for this issue:
- we add some tests here, related to morpho-v1
- we create a new repo just for these tests (in which we can tests everything else, MORPHO token, etc etc, and every change to it).

**Comment by MerlinEgalite** [comment]
Moved to https://github.com/morpho-org/morpho-seatbelt
